### ISSUE TITLE
Extension Host Crashing

### ISSUE THREAD

**Issue by mpearon** [JohnstonCode/svn-scm#1040]
- VSCode Version: 1.48.0 / 1.48.0-insider
- OS Version: Win10 1909
- Extension Version: v2.12.3
- System Language: English
- SVN Version: 1.12.2 (r1863366)

## Issue ##
Extension Use or SVN use outside of vsCode is causing Extension Host to crash

### Method 1
1. Launch vsCode
2. Perform SVN Add
3. vsCode Extension Host crashes

### Method 2
1. Launch vsCode
2. Launch PowerShell
3. Navigate to repo location in PowerShell
3. Issue ``` svn add . ``` within PowerShell
4. vsCode Extension Host crashes

## Console Output ##
```
localProcessExtensionHost.ts:233 Extension Host
localProcessExtensionHost.ts:234 c:\Users\*******************\.vscode\extensions\johnstoncode.svn-scm-2.12.3\out\extension.js:10
const r=n(15),o=n(69),i=n(2),s=n(54),a={fs:r.constants,os:o.constants},c=n(142),u="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",h=/XXXXXX/,l=(a.O_CREAT||a.fs.O_CREAT)|(a.O_EXCL||a.fs.O_EXCL)|(a.O_RDWR||a.fs.O_RDWR),p="win32"===o.platform(),d=a.EBADF||a.os.errno.EBADF,f=a.ENOENT||a.os.errno.ENOENT,m=[],g=r.rmdirSync.bind(r),y=c.sync;let w=!1;function v(t,e){const n=T(t,e),o=n[0],i=n[1];try{x(o)}catch(t){return i(t)}let s=o.tries;!function t(){try{const e=P(o);r.stat(e,(function(n){if(!n)return s-- >0?t():i(new Error("Could not get a unique tmp filename, max tries reached "+e));i(null,e)}))}catch(t){i(t)}}()}function E(t){const e=T(t)[0];x(e);let n=e.tries;do{const t=P(e);try{r.statSync(t)}catch(e){return t}}while(n-- >0);throw new Error("Could not get a unique tmp filename, max tries reached")}function b(t,e){const n=function(t){if(t&&!F(t))return e(t);e()};0<=t[0]?r.close(t[0],(function(){r.unlink(t

[TypeError: Cannot read property 'fire' of undefined
	at FSWatcher.repoWatch (c:\Users\*******************\.vscode\extensions\johnstoncode.svn-scm-2.12.3\out\extension.js:10:75596)
	at Timeout._onTimeout (c:\Users\*******************\.vscode\extensions\johnstoncode.svn-scm-2.12.3\out\extension.js:1:29771)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)] {
  vslsStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {} ]
}
```

## Screenshots ##
N/A

**Comment by mpearon** [comment]
More information:
Embarrassingly, this might be an environmental issue.  I've disabled all of my extensions and the issue seems to be fixed.  I'm systematically re-enabling to see if I can track down which one is causing the issue.

**Comment by mpearon** [comment]
More Information:
It looks like this might be related to the [Code Time](https://github.com/swdotcom/swdc-vscode) plugin.  It looks like there are [existing issues](https://github.com/swdotcom/swdc-vscode/issues/113) related to a bug there.
