### ISSUE TITLE
Support for legacy `SVN_ASP_DOT_NET_HACK` environment variable

### ISSUE THREAD

**Issue by jimbobmcgee** [JohnstonCode/svn-scm#1156]
- VSCode Version: 1.50.1
- OS Version: Win10 x64 (10.0.18363)
- Extension Version: 2.13.3
- System Language: UK English
- SVN Version: 1.11.1

## Issue ##
There is a legacy environment variable baked into Subversion which, if set, changes the working folder's magic directory from `.svn` to `_svn`.  It was implemented in the days of yore, when Visual Studio .NET 2002 (and 2003) would crash and burn on dot-prefixed folder names.  It was officially ratified in the release notes of Subversion 1.3 https://subversion.apache.org/docs/release-notes/1.3.html#_svn-hack.

Unfortunately, because I genuinely still have to support clients with a legacy ASP.NET 1.1 application (whether I like it or not), I have to have that variable set, so all my Subversion working folders use the `_svn` form, not the `.svn` form.

I *think* that this extension tests for the existence of a `.svn` directory in the workspace to determine whether to enable itself and, because I don't have this directory, the icon disappears and no SCM integration is available.

If I *manually* tweak a repository working folder, i.e. to rename `_svn` to `.svn`, I can see an error in the VSCode Developer Tools console -- it looks to be reflected from the `svn.exe` call itself, because `svn.exe` still expects the working copy to be `_svn`.

```
console.ts:137 [Extension Host]% 
{message: "Failed to execute svn", stdout: "<?xml version="1.0" encoding="UTF-8"?>
↵<info>
↵", stderr: "svn: E155007: 'D:\Projects\myproj\trunk' is not a working copy
↵", stderrFormated: "'D:\Projects\myproj\trunk' is not a working copy
↵", exitCode: 1, …}
exitCode: 1
message: "Failed to execute svn"
stderr: "svn: E155007: 'D:\Projects\myproj\trunk' is not a working copy
↵"
stderrFormated: "'D:\Projects\Personal\wstunnel\trunk' is not a working copy
↵"
stdout: "<?xml version="1.0" encoding="UTF-8"?>
↵<info>
↵"
svnCommand: "info"
svnErrorCode: "E155007"
__proto__: Object
```

## Steps to Reproduce ##

1. Be on Windows
2. Configure the system-wide environment variable, `SVN_ASP_DOT_NET_HACK`, with any value (I use `*` myself), using the Control Panel (or <kbd>WIN</kbd><kbd>R</kbd> `rundll32.exe sysdm.cpl,EditEnvironmentVariables`)
3. Check out a repository to a new working directory (you should see an `_svn` hidden folder instead of a `.svn` hidden folder)
4. Open the checked-out working directory as a VSCode workspace
5. Subversion extension is not activated

(Note that you will want to revert the `SVN_ASP_DOT_NET_HACK` variable before using any of your existing working folders, as both TortoiseSVN and `svn.exe` will stop recognising these if this variable is set.)

## Possible Fix ##
There is a function in https://github.com/JohnstonCode/svn-scm/blob/06a6b0ce9cdd9a1045b9b2e45515b3356b9aa6fd/src/util.ts#L184 called `isSvnFolder`, which looks like it performs the directory-exists check.  I don't know if this is used universally but, if it is, it might be enough to include a check for the environment variable there (*Technically*, it should also be constrained to running on the Windows OS, but I doubt many people will have set this variable and *not* be running Windows):

```
export async function isSvnFolder(
  dir: string,
  checkParent: boolean = true
): Promise<boolean> {
  const dotFolder = (!!process.env["SVN_ASP_DOT_NET_HACK"]) ? "_svn" : ".svn"; 
  const result = await exists(`${dir}/${dotFolder}`);

  if (result || !checkParent) {
    return result;
  }

  const parent = path.dirname(dir);

  // For windows: the `path.dirname("c:")` return `c:`
  // For empty or doted dir, return "."
  if (parent === dir || parent === ".") {
    return false;
  }

  return isSvnFolder(parent, true);
}
```

I haven't submitted as a PR, because I don't have a suitable development environment set up for VSCode extensions, so haven't tested the above.  My Github-fu is also letting me down with regards to whether there are any other places where `.svn` is explicitly referenced.

**Comment by JohnstonCode** [comment]
I'll look at adding this by the end of the week.

**Comment by JohnstonCode** [comment]
Can you manually install this vsix and test it works please?
https://github.com/JohnstonCode/svn-scm/suites/1575259798/artifacts/28437948

**Comment by jimbobmcgee** [comment]
Thanks for this, but it looks like `.svn` has been hard-coded in more than just the `isSvnFolder` routine.

```
console.ts:137 [Extension Host] Error: ENOENT: no such file or directory, watch 'D:\Projects\myproj\.svn'
	at FSWatcher.start (internal/fs/watchers.js:165:26)
	at Object.watch (fs.js:1329:11)
	at new h (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:272631)
	at new b (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:207337)
	at g.tryOpenRepository (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:231261)
	at async g.scanWorkspaceFolders (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:230908)
	at async g.enable (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:229484)
	at async d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:228206
	at async d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:167786
	at async _ (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:167633)
	at async d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:169209
	at async e.activate (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:167427)
```

From what I can tell, we will also need logic in at least...
 * https://github.com/JohnstonCode/svn-scm/blob/6b3521a08cf2d3ef4a57ec0f46c0c271924f3933/src/watchers/repositoryFilesWatcher.ts#L52
 * https://github.com/JohnstonCode/svn-scm/blob/6b3521a08cf2d3ef4a57ec0f46c0c271924f3933/src/watchers/repositoryFilesWatcher.ts#L65
 * https://github.com/JohnstonCode/svn-scm/blob/6b3521a08cf2d3ef4a57ec0f46c0c271924f3933/src/watchers/repositoryFilesWatcher.ts#L79

**Comment by JohnstonCode** [comment]
Yeah sorry about that. Can you give this one a try.
https://github.com/JohnstonCode/svn-scm/suites/1603531914/artifacts/29272192

**Comment by jimbobmcgee** [comment]
@JohnstonCode: Yes, that version seems to be functioning.  I can see and check in changes via the main SCM side panel, and can see log messages and branch changes in the dedicated Subversion panel, which I think is largely what is expected.

Note that I am still seeing the below error in the dev tools, but I don't know if it is related to this specific issue (I suspect not):

```
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'fire' of undefined
$onExtensionRuntimeError @ terminalInstanceService.ts:31
-----------
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'fire' of undefined
	at FSWatcher.repoWatch (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:278050)
	at Timeout._onTimeout (d:\Users\jimbobmcgee\.vscode\extensions\johnstoncode.svn-scm-2.13.5\out\extension.js:2:169809)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
```

**Comment by jimbobmcgee** [comment]
@JohnstonCode - did this go into v2.13.6?  I have a sneaking suspicion it did *not*, and that vscode has updated the manually-installed version above to a version where this no longer works...

**Comment by JohnstonCode** [comment]
It did not make it into v2.13.6. If you are happy its working i can pushed a release with this change.

**Comment by JohnstonCode** [comment]
I think the only change i would make to the PR is to move `SVN_ASP_DOT_NET_HACK` to be a config option in the extension settings. That way you can set it per workspace, thoughts?

**Comment by jimbobmcgee** [comment]
Hi @JohnstonCode; not sure making a config option is the right thing.  Your call, of course, but hear me out... :-)

`SVN_ASP_DOT_NET_HACK` is an machine-wide environment variable understood by Subversion, rather than a setting to be understood by VSCode.  If it's set (to any value) then both `svn.exe` and TortoiseSVN (for example) will expect `_svn` metadata folders in working folders, instead of `.svn`.  

Since (I think) you integrate with these to do your own SVN operations, any mismatch between the environment variable `SVN_ASP_DOT_NET_HACK` and your workspace config setting is going to cause issues, only now there are four combinations to worry about (*env&cfg*, *env&!cfg*, *!env&cfg* and *!env&!cfg*) and only two would be correct.

The PR you wrote was to enable your plugin to detect when this env var was set and activate the plugin in workspaces which had `_svn` folders, rather than hard-coding searching for `.svn` folders -- i.e. to match the behaviour of the SVN apps.
