### ISSUE TITLE
TypeError: t.replace is not a function

### ISSUE THREAD

**Issue by briankueck** [JohnstonCode/svn-scm#1579]
- VSCode Version: 1.68.1 (Latest)
- Extension Version: 2.15.5 (Latest)

## Issue ##

 [renderer1] [error] [Extension Host] TypeError: t.replace is not a function
	at d (c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:273523)
	at Object.e.normalizePath (c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:273739)
	at c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:235072
	at Array.map (<anonymous>)
	at g.tryOpenRepository (c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:235062)
	at async g.scanWorkspaceFolders (c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:234820)
	at async g.enable (c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:233396)
	at async c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:232118
	at async c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:363542
	at async _ (c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:363389)
	at async c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:364965
	at async t.activate (c:\Users\...\.vscode\extensions\johnstoncode.svn-scm-2.15.5\out\extension.js:2:363183)
	at async _activate (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8122)
	at async _initialize (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:7486)

## Steps to Reproduce ##

1. Load VS Code.
2. Install the latest SVN extension from Chris Johnston v2.15.5
3. Look at the VS Code Output window. 
4. It shows there is an error in the code: t.replace is not a function

**Comment by JohnstonCode** [comment]
![image](https://user-images.githubusercontent.com/10222719/181775599-0aaf54a1-fe9f-4e73-aadf-da26066a1a03.png)

unable to replicate
