### ISSUE TITLE
“source control graph” runs continuously

### ISSUE THREAD

**Issue by mixo712** [JohnstonCode/svn-scm#1645]
- VSCode Version: 1.94.1
- OS Version: Windows 10 Business 22H2
- Extension Version: v2.17.0
- System Language: French
- SVN Version: VisualSVN Server 5.0.2 (server) / TortoiseSVN 1.11.1 (client)

## Issue ##
Since VsCode 1.94.1 update, “source control graph” runs continuously in the "Source controle" extension tab but seems to be OK in the Explorer/SVN tab

## Steps to Reproduce ##

1. update VsCode  to 1.94.1
2. Run VsCode on my SVN folder

## SVN Output ##
(folders and file names are renamed for privacy)
```
Using svn "1.11.1" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[myRepository]$ svn info --xml 'c:\Users\myUserName\OneDrive - mycompany.com\myWorkspace\myRepository\MyEnv\mySchema\myFolder\PACKAGE\pkg_xxx_yyy.sql'
[myRepository]$ svn list 'c:\Users\myUserName\OneDrive - mycompany.com\myWorkspace\myRepository\MyEnv\mySchema\myFolder\PACKAGE\pkg_xxx_yyy.sql' --xml
[myRepository]$ svn info --xml
[myRepository]$ svn stat --xml --no-ignore --ignore-externals
[myRepository]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[myRepository]$ svn info --xml
[myRepository]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[myRepository]$ svn info --xml
```

![image](https://github.com/user-attachments/assets/a8e0c18e-a0d8-4467-b73e-0b9e1fad3e9f)
![image](https://github.com/user-attachments/assets/52d00372-7ffa-49b9-b3ee-4d59a2429d22)

Thanks for help.

**Comment by suchja** [comment]
Same here on macOS
- VSCode Version: 1.94.2
- OS Version: macOS 15.0.1
- Extension Version: v2.17.0
- System Language: English
- SVN Version: SVN 1.14.3 installed via homebrew (client)

As I just started using this extension I cannot say whether the problem existed before.

**Comment by Foxlider** [comment]
Same here on Windows

- VSCode Version: 1.94.2 (user setup)
- OS: Windows_NT x64 10.0.22621
- Extension Version: v2.17.0
- System Language : French
- SVN Version: svn, version 1.13.0 (r1867053)

Each time the tree is refreshed, I get the folowing output : 
```log
2024-10-25 08:53:22.091 [error] TreeError [SCM History Tree] Tree input not set: Error: TreeError [SCM History Tree] Tree input not set
    at lf.C (vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:405:31129)
    at lf.updateChildren (vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:405:31036)
    at vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:2142:14608
    at r (vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:1261:10985)
    at R8e.D (vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:1261:15861)
    at R8e.z (vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:1261:15120)
    at o (vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:1261:11211)
    at R8e.withProgress (vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:1261:11313)
    at vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:2142:14553
    at vscode-file://vscode-app/c:/{{VS_FOLDER}}/vs/workbench/workbench.desktop.main.js:31:71664
```

**Comment by artejera** [comment]
Hi ....
Same here, debian 11, vscode 1.94.2.  extension v2.17.0.   
Best regards

**Comment by Xcodo** [comment]
This may be related to this, which appeared around the same time:
microsoft/vscode#232396

**Comment by mixo712** [comment]
Hi,
Issue can be closed because it seems to be fixed with last VScode updates (dont know what version exactly).
Thanks.
