### ISSUE TITLE
Proposed API is only available when running out of dev

### ISSUE THREAD

**Issue by bardware** [JohnstonCode/svn-scm#327]
- VSCode Version: 1.27.1
- OS Version: Windows 10 64bit 
- Extension Version: 1.33.0
- System Language: German
- SVN Version: `svn, Version 1.9.7-SlikSvn (SlikSvn/1.9.7)`

## Issue ##

I happened to look into the developer console in VSCode and saw the following exception.
Does it influence the usability of your plugin? I'd like to see the blame view for a file but don't see anything and wonder if I'm using it the wrong way.

```
Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api johnstoncode.svn-scm: Error: [johnstoncode.svn-scm]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api johnstoncode.svn-scm
	at ee (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:795:383)
	at new SvnDecorationProvider (C:\vscode\cfml\exts\johnstoncode.svn-scm-1.33.0\out\decorations\svnDecorationProvider.js:12:47)
	at SvnDecorations.onDidOpenRepository (C:\vscode\cfml\exts\johnstoncode.svn-scm-1.33.0\out\decorations\svnDecorations.js:41:26)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:937)
	at Model.open (C:\vscode\cfml\exts\johnstoncode.svn-scm-1.33.0\out\model.js:282:35)
	at Model.<anonymous> (C:\vscode\cfml\exts\johnstoncode.svn-scm-1.33.0\out\model.js:195:26)
	at Generator.next (<anonymous>)
	at fulfilled (C:\vscode\cfml\exts\johnstoncode.svn-scm-1.33.0\out\model.js:10:58)
	at <anonymous>
```

**Comment by edgardmessias** [comment]
Caused by 014eaa9, changed `hasDecorationProvider = false` to `hasDecorationProvider = true`

**Comment by edgardmessias** [comment]
Thanks @bardware for reporting
