### ISSUE TITLE
Diff Changes HEAD is not working

### ISSUE THREAD

**Issue by magic-k** [JohnstonCode/svn-scm#40]
- VSCode Version: 1.18.1
- OS Version: Windows10/Ubuntu 14.4
- Extension Version: 1.0.1
- System Language: german

Steps to Reproduce:

1. Goto SCM Explorer
2. Right mouse on a modified file
3. Select "Diff Changes HEAD" from context menu

Result: Nothing

The Editor shows the decorations for changes correctly and the quick diff works.

**Comment by s-martin** [comment]
Dito for CentOS 7.4

**Comment by JohnstonCode** [comment]
Do you get anything in the error log?

**Comment by magic-k** [comment]
[johnstoncode.svn-scm] Running the contributed command:'vscode.diff' failed. Illegal argument 'left' - Left-hand side resource of the diff editor: Error: Running the contributed command:'vscode.diff' failed. Illegal argument 'left' - Left-hand side resource of the diff editor
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:411939)
	at e.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:411279)
	at Object.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:488349)
	at SvnCommands.<anonymous> (C:\Users\magick\.vscode\extensions\johnstoncode.svn-scm-1.0.1\out\commands.js:230:41)
	at Generator.next (<anonymous>)
	at C:\Users\magick\.vscode\extensions\johnstoncode.svn-scm-1.0.1\out\commands.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\magick\.vscode\extensions\johnstoncode.svn-scm-1.0.1\out\commands.js:3:12)
	at SvnCommands.openResource (C:\Users\magick\.vscode\extensions\johnstoncode.svn-scm-1.0.1\out\commands.js:204:16)
	at SvnCommands.<anonymous> (C:\Users\magick\.vscode\extensions\johnstoncode.svn-scm-1.0.1\out\commands.js:199:22)

**Comment by JohnstonCode** [comment]
ummmmm

Not a clue why that has stopped working.

Working on this now

**Comment by s-martin** [comment]
@magic-k: dito

**Comment by JohnstonCode** [comment]
Fixed in v1.0.2

Seems i added async when it wasn't needed.
