### ISSUE TITLE
Error in console readdirSync failed (vscode freeze)

### ISSUE THREAD

**Issue by llgcode** [JohnstonCode/svn-scm#503]
- VSCode Version: 1.32.3
- OS Version: win10
- Extension Version: 1.47.3
- System Language:
- SVN Version:

## Issue ##

debugging my own extension seen a lot of errors from your extension, I suspect your extension to have some performance issue. When saving a file my vscode freeze , asking me if readdirSync is appropriate here? if I disable your extension I don't have any freeze in vscode.

stack trace: Error: ENOTDIR: not a directory, scandir '**********************something.js'
extensionHostProcess.js:700
	at Object.fs.readdirSync (fs.js:893:3)
	at Object.exports.wrapFsWithAsar.fs.readdirSync (ELECTRON_ASAR.js:633:28)
	at Model.<anonymous> (C:\Users\anonymous\.vscode\extensions\johnstoncode.svn-scm-1.47.3\out\model.js:224:39)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Users\anonymous\.vscode\extensions\johnstoncode.svn-scm-1.47.3\out\model.js:13:71)
	at new module.exports.t.exports (C:\Users\anonymous\.vscode\extensions\vscjava.vscode-java-dependency-0.3.0\dist\extension.js:1:119598)
	at __awaiter (C:\Users\anonymous\.vscode\extensions\johnstoncode.svn-scm-1.47.3\out\model.js:9:12)
	at Model.tryOpenRepository (C:\Users\anonymous\.vscode\extensions\johnstoncode.svn-scm-1.47.3\out\model.js:182:16)
	at Model.eventuallyScanPossibleSvnRepositories (C:\Users\anonymous\.vscode\extensions\johnstoncode.svn-scm-1.47.3\out\model.js:106:18)
	at Timeout.decorate.(anonymous function).setTimeout [as _onTimeout] (C:\Users\anonymous\.vscode\extensions\johnstoncode.svn-scm-1.47.3\out\decorators.js:86:50)
	at ontimeout (timers.js:427:11)
	at tryOnTimeout (timers.js:289:5)
	at listOnTimeout (timers.js:252:5)
	at Timer.processTimers (timers.js:212:10)

**Comment by JohnstonCode** [comment]
Yeah i should be checking stuff is a dir and also stop using sync calls

**Comment by JohnstonCode** [comment]
Can you update to v1.47.5 and let me know if you are still having this issue?

**Comment by llgcode** [comment]
Hi @JohnstonCode, it seems to be better. No more errors messages in the console and no more freeze. 
Thank you for your reactivity!! :-)
