### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by liushiqi9** [JohnstonCode/svn-scm#611]
- VSCode Version: 1.35.1
- OS Version: arch: windows 7 
- Extension Version: 1.53.0
- System Language: 
- SVN Version:

## Steps to Reproduce ##

1. Install Remote extension packages in vscode
2. Connect to a Arch Server with svn.
3. Install SVN extension.
4. Open a folder with .svn inside.
5. click on svn sidebars.

## SVN Output ##
"Cannot read property 'split' of undefined." Message pops.
Repository on the left won't unfold.

**Comment by liushiqi9** [comment]
Solved with VSCode 1.36.0 and SVN 1.54.3

**Comment by liushiqi9** [comment]
False close, still exist with VSCode 1.36.0 and SVN 1.54.3.

**Comment by edgardmessias** [comment]
Go to "Help >> Toggle developer tools >> console" Do you have any svn-scm errors?

**Comment by liushiqi9** [comment]
> Go to "Help >> Toggle developer tools >> console" Do you have any svn-scm errors?

I checked, only Split undefined is showed in  Toggle developer tools >> console. 
I have three svn repositories in same folder as three subfolder. 
The problem is showed when I click the svn sidebar and then click on one svn repository to see the svn logs. 
Among the three svn repositories, one of them I can see the svn logs. The other two show the "Cannot read property 'split' of undefined." instead. I assum it's because they cannot read the svn logs, and has nothing to show me, and then triggered a js error. 
So I go to the Output to see what did svn do. And I can see that three repositories all called a command like "svn log -r HEAD:1 --limit=10" with different path. I copied three commands into bash shell and they all returned with a correct xml output.

**Comment by liushiqi9** [comment]
I suspect it's timeout related, is threre a timeout setting when svn plugin calling svn log?

**Comment by liushiqi9** [comment]
Currently I suspect it's because vscode svn extension is not using the correct username, so it has problem with folder with access control, is there a way that I can verify my suspection ？

**Comment by liudonghua123** [comment]
I have the same issue with the latest vscode and svn extension.

```
workbench.desktop.main.js:sourcemap:2542 Error: Cannot read property 'split' of undefined
    at Object.getCommitLabel (c:\Users\Liu.D.H\.vscode\extensions\johnstoncode.svn-scm-1.54.5\out\historyView\common.js:173:32)
    at RepoLogProvider.<anonymous> (c:\Users\Liu.D.H\.vscode\extensions\johnstoncode.svn-scm-1.54.5\out\historyView\repoLogProvider.js:299:53)
    at Generator.next (<anonymous>)
    at __awaiter (c:\Users\Liu.D.H\.vscode\extensions\johnstoncode.svn-scm-1.54.5\out\historyView\repoLogProvider.js:7:71)
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\Liu.D.H\.vscode\extensions\johnstoncode.svn-scm-1.54.5\out\historyView\repoLogProvider.js:3:12)
    at RepoLogProvider.getTreeItem (c:\Users\Liu.D.H\.vscode\extensions\johnstoncode.svn-scm-1.54.5\out\historyView\repoLogProvider.js:275:16)
    at define.fetchChildrenNodes.a.asPromise.then.Promise.all.u.coalesce.map.a.asPromise (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:504:138)
    at t.asPromise.Promise (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:720)
    at new Promise (<anonymous>)
    at Object.t.asPromise (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:692)
    at define.fetchChildrenNodes.a.asPromise.then.Promise.all.u.coalesce.map.e (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:504:106)
    at Array.map (<anonymous>)
    at define.fetchChildrenNodes.a.asPromise.then.e (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:504:97)
```

![image](https://user-images.githubusercontent.com/2276718/66370599-685ff080-e9d3-11e9-854b-b21f309338b5.png)

**Comment by JohnstonCode** [comment]
Do you have blank commit messages?

**Comment by liudonghua123** [comment]
@JohnstonCode I did saw some empty commit messages.

**Comment by JohnstonCode** [comment]
I'll have a look at this tonight.
