### ISSUE TITLE
Issues with v 1.54.1

### ISSUE THREAD

**Issue by mcherndon68** [JohnstonCode/svn-scm#619]
- VSCode Version: 1.35.1
- OS Version: Windows 10 64-bit
- Extension Version: 1.54.1
- System Language: 
- SVN Version:

## Issue ##
Can't see files in source-control page
## Steps to Reproduce ##

Not sure about reproducing.  But whenever I go to the source control I get this in the 'Log (Window)' of output.

[2019-06-26 10:57:47.437] [renderer1] [error] Cannot read property 'match' of undefined: TypeError: Cannot read property 'match' of undefined
	at Object.getBranchName (C:\Users\mherndon\.vscode\extensions\johnstoncode.svn-scm-1.54.1\out\helpers\branch.js:30:32)
	at Repository.<anonymous> (C:\Users\mherndon\.vscode\extensions\johnstoncode.svn-scm-1.54.1\out\svnRepository.js:249:37)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\mherndon\.vscode\extensions\johnstoncode.svn-scm-1.54.1\out\svnRepository.js:10:58)

**Comment by JohnstonCode** [comment]
Can you copy the svn output?

**Comment by mcherndon68** [comment]
Something you did with the last update fixed it.  Unrelated I'm sure.  But
I forgot to close the ticket.

**Comment by JohnstonCode** [comment]
Glad its now working for you.
